"""ChromaDB-backed memory bank to persist teacher feedback grounded in neural state."""

from typing import Any, Dict, List, Optional
import time


class MemoryBank:
    def __init__(self, collection: str = "ego_memories", persist_directory: Optional[str] = None) -> None:
        # Lazy import to avoid hard dependency issues during environments that
        # lack compatible chromadb/pydantic builds.
        try:
            import chromadb
            from chromadb.config import Settings
        except Exception as exc:  # pragma: no cover - env specific
            raise RuntimeError(f"ChromaDB unavailable: {exc}") from exc

        # Disable telemetry and allow optional persistence directory.
        settings_kwargs = {"anonymized_telemetry": False}
        if persist_directory:
            settings_kwargs["persist_directory"] = persist_directory
        self._client = chromadb.Client(Settings(**settings_kwargs))
        self._collection = self._client.get_or_create_collection(name=collection)

    def add_memory(
        self,
        content: str,
        embedding: List[float],
        metadata: Optional[Dict[str, Any]] = None,
        doc_id: Optional[str] = None,
    ) -> str:
        """Store a document with embedding and metadata.

        Args:
            content: The textual content to store (e.g., teacher reply).
            embedding: Neural state embedding (e.g., assoc spikes) as float list.
            metadata: Arbitrary key/values to track context (timestamp, trigger type).
            doc_id: Optional external id; autogenerated if omitted.

        Returns:
            The document id used for storage.
        """

        meta = metadata or {}
        if "timestamp" not in meta:
            meta["timestamp"] = time.time()

        doc_id = doc_id or f"mem-{int(time.time() * 1e6)}"
        self._collection.add(documents=[content], embeddings=[embedding], metadatas=[meta], ids=[doc_id])
        return doc_id

    def count(self) -> int:
        return self._collection.count()


__all__ = ["MemoryBank"]
